# Generated by Django 4.1.3 on 2022-12-16 14:06

# Third-Party Libraries
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dataAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiuser",
            name="refresh_token",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
