# Generated by Django 4.1.5 on 2023-05-05 20:15

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_teammembers_team_member_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwOrgsAllIps',
            fields=[
                ('organizations_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('cyhy_db_name', models.TextField(blank=True, null=True)),
                ('ip_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'vw_orgs_all_ips',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='team_member_uid',
            field=models.UUIDField(default=uuid.UUID('8c3dca17-eb81-11ed-aaa5-37ca8d677a21'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weeklystatuses',
            name='weekly_status_uid',
            field=models.UUIDField(default=uuid.UUID('8c3dca20-eb81-11ed-aaa5-37ca8d677a21'), primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='vworgstotalips',
            table='mat_vw_orgs_total_ips',
        ),
    ]
