# Generated by Django 4.1.5 on 2023-05-05 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vworgsallips_alter_teammembers_team_member_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='team_member_uid',
            field=models.UUIDField(default=uuid.UUID('1f97df69-eb82-11ed-aaa5-37ca8d677a21'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weeklystatuses',
            name='weekly_status_uid',
            field=models.UUIDField(default=uuid.UUID('1f97df72-eb82-11ed-aaa5-37ca8d677a21'), primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='vworgstotalips',
            table='mat_vw_orgs_all_ips',
        ),
    ]
