"""home module migrations/0005.py."""
# Generated by Django 4.1.5 on 2023-05-05 20:24

# Standard Python Libraries
import uuid

# Third-Party Libraries
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class."""

    dependencies = [
        ("home", "0004_alter_teammembers_team_member_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembers",
            name="team_member_uid",
            field=models.UUIDField(
                default=uuid.UUID("cb1096bf-eb82-11ed-aaa5-37ca8d677a21"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="weeklystatuses",
            name="weekly_status_uid",
            field=models.UUIDField(
                default=uuid.UUID("cb1096c8-eb82-11ed-aaa5-37ca8d677a21"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterModelTable(
            name="vworgsallips",
            table="mat_vw_orgs_all_ips",
        ),
        migrations.AlterModelTable(
            name="vworgstotalips",
            table="vw_orgs_total_ips",
        ),
    ]
